Add the 'xhtmlv' command to utils/skrelease

diff --git a/utils/skrelease b/utils/skrelease
--- a/utils/skrelease
+++ b/utils/skrelease
@@ -69,6 +69,58 @@ test_disassemblies() {
 }
 
 ###############################################################################
+# Run validate-xhtml on the ROM/HH/MM/JSW/SD/BTS/CSC disassemblies
+###############################################################################
+_run_validate_xhtml() {
+  projhome=$1
+  target=$2
+  htmldir=$3
+
+  builddir=$projhome/build/html
+  buildlog=$builddir/$target.log
+  htmllog=$builddir/$htmldir.log
+  rm -rf $builddir/$htmldir $buildlog $htmllog
+  mkdir -p $builddir
+  make -C $projhome $target &> $buildlog &&
+  $TOOLS/validate-xhtml $builddir/$htmldir &> $htmllog
+}
+
+_wait_validate_xhtml() {
+  name=$1
+  pid=$2
+  projhome=$3
+  target=$4
+  htmldir=$5
+
+  builddir=$projhome/build/html
+  htmllog=$builddir/$htmldir.log
+  echo -n "$name validate-xhtml: "
+  if wait $pid; then
+    [[ -s $htmllog ]] && echo "VALIDATION FAILED (see $htmllog)" || echo "OK"
+  else
+    echo "BUILD FAILED (see $builddir/$target.log)"
+  fi
+}
+
+validate_xhtml() {
+  _run_validate_xhtml $SKOOLKIT_HOME rom rom & PIDrom=$!
+  _run_validate_xhtml $SKOOLKIT_HOME hh hungry_horace & PIDhh=$!
+  _run_validate_xhtml $MANICMINER_HOME mm manic_miner & PIDmm=$!
+  _run_validate_xhtml $JETSETWILLY_HOME jsw jet_set_willy & PIDjsw=$!
+  _run_validate_xhtml $DISASSEMBLIES_HOME sd skool_daze & PIDsd=$!
+  _run_validate_xhtml $DISASSEMBLIES_HOME bts back_to_skool & PIDbts=$!
+  _run_validate_xhtml $DISASSEMBLIES_HOME csc contact_sam_cruise & PIDcsc=$!
+
+  _wait_validate_xhtml "Spectrum ROM" $PIDrom $SKOOLKIT_HOME rom rom
+  _wait_validate_xhtml "Hungry Horace" $PIDhh $SKOOLKIT_HOME hh hungry_horace
+  _wait_validate_xhtml "Manic Miner" $PIDmm $MANICMINER_HOME mm manic_miner
+  _wait_validate_xhtml "Jet Set Willy" $PIDjsw $JETSETWILLY_HOME jsw jet_set_willy
+  _wait_validate_xhtml "Skool Daze" $PIDsd $DISASSEMBLIES_HOME sd skool_daze
+  _wait_validate_xhtml "Back to Skool" $PIDbts $DISASSEMBLIES_HOME bts back_to_skool
+  _wait_validate_xhtml "Contact Sam Cruise" $PIDcsc $DISASSEMBLIES_HOME csc contact_sam_cruise
+}
+
+###############################################################################
 # Run disassembly-diff on the MM/JSW/SD/BTS/CSC disassemblies
 ###############################################################################
 disassembly_diffs() {
@@ -162,6 +214,7 @@ Usage: $(basename $0) COMMAND
 
 COMMAND may be one of:
   dtests - run the disassemblies (MM/JSW/SD/BTS/CSC) tests
+  xhtmlv - run validate-xhtml on the ROM/HH/MM/JSW/SD/BTS/CSC disassemblies
   ddiffs - run disassembly-diff on the MM/JSW/SD/BTS/CSC disassemblies
   asmchk - run check-asms on the MM/JSW/SD/BTS/CSC disassemblies
 EOM
@@ -172,6 +225,7 @@ EOM
 ###############################################################################
 case "$1" in
   dtests) test_disassemblies ;;
+  xhtmlv) validate_xhtml ;;
   ddiffs) disassembly_diffs ;;
   asmchk) check_asms ;;
        *) usage ;;
