Check the presence of required variables in tools/drelease-functions

diff --git a/tools/drelease-functions b/tools/drelease-functions
--- a/tools/drelease-functions
+++ b/tools/drelease-functions
@@ -1,6 +1,21 @@
-DIFFSBUILD=$DHOME/build/disassembly-diff
+for vname in DHOME GAME GAMENAME GHREPO SKOOLKIT_ARCHIVE SRCFILES; do
+  value=$(eval echo \$$vname)
+  if [[ -z $value ]]; then
+    echo "$vname is not set; aborting"
+    exit 1
+  fi
+done
+
+for vname in DHOME SKOOLKIT_ARCHIVE; do
+  value=$(eval echo \$$vname)
+  if [[ ! -d $value ]]; then
+    echo "$vname=$value: directory not found"
+    exit 1
+  fi
+done
 
 BUILD=$DHOME/build
+DIFFSBUILD=$BUILD/disassembly-diff
 DIST=$DHOME/dist
 DTMPDIR=$HOME/tmp
 REF=$DHOME/sources/$GAME.ref
@@ -8,21 +23,7 @@ VERSION=$(grep ^Release= $REF | awk '{print $NF}')
 RELEASE=$GAME-disassembly-$VERSION
 SKOOLKIT_TOOLS=$SKOOLKIT_HOME/tools
 SKOOLKIT_VERSION=$(cd $SKOOLKIT_HOME; git tag | tail -n 1 | cut -c2-)
-
-###############################################################################
-# Check required environment variables
-###############################################################################
-_require_skoolkit_archive() {
-  if [[ -z $SKOOLKIT_ARCHIVE ]]; then
-    echo 'SKOOLKIT_ARCHIVE is not set; aborting'
-    exit 1
-  fi
-  if [[ ! -d $SKOOLKIT_ARCHIVE ]]; then
-    echo "SKOOLKIT_ARCHIVE=$SKOOLKIT_ARCHIVE: directory not found"
-    exit 1
-  fi
-  SKOOLKIT_TARBALL=$SKOOLKIT_ARCHIVE/skoolkit-$SKOOLKIT_VERSION.tar.xz
-}
+SKOOLKIT_TARBALL=$SKOOLKIT_ARCHIVE/skoolkit-$SKOOLKIT_VERSION.tar.xz
 
 ###############################################################################
 # Utility functions
@@ -118,8 +119,6 @@ check_asms() {
 # Make a TAP file from an ASM file and load it
 ###############################################################################
 check_tap() {
-  _require_skoolkit_archive
-
   binfile=$DIFFSBUILD/disassembly-current-$SKOOLKIT_VERSION/asm/$1.bin
   tapfile=$(basename $binfile .bin).tap
   _cd_tmpdir
@@ -140,8 +139,6 @@ skooldiff() {
 # Build the disassembly distribution tarball and zip archive
 ###############################################################################
 build_tarball() {
-  _require_skoolkit_archive
-
   _cd_tmpdir
   logdir=$(pwd)
   tar xf $SKOOLKIT_TARBALL
@@ -163,8 +160,6 @@ build_tarball() {
 # Update the HTML disassembly on the gh-pages branch
 ###############################################################################
 update_ghpages() {
-  _require_skoolkit_archive
-
   mkdir -p $BUILD
   htmldir=$BUILD/html/$(grep ^GameDir= $REF | cut -c9-)
   skdir=$BUILD/skoolkit-$SKOOLKIT_VERSION
@@ -198,8 +193,6 @@ EOM
 # Run the disassembly tests
 ###############################################################################
 test_disassembly() {
-  _require_skoolkit_archive
-
   _cd_tmpdir
   logdir=$(pwd)
   tar xf $SKOOLKIT_TARBALL
