Add the 'rpmpkg' command to tools/skrelease

diff --git a/tools/skrelease b/tools/skrelease
--- a/tools/skrelease
+++ b/tools/skrelease
@@ -42,6 +42,8 @@ fi
 
 TOOLS=$SKOOLKIT_HOME/tools
 SKTMPDIR=$HOME/tmp
+VERSION=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
+TARBALL=$SKOOLKIT_HOME/dist/skoolkit-$VERSION.tar.xz
 
 ###############################################################################
 # Utility functions
@@ -123,6 +125,44 @@ _check_examples() {
   logdir=$2
 
   _check_files examples $rootdir $logdir 48.rom.{ctl,ref} hungry_horace.{ctl,ref,t2s}
+}
+
+_build_pkg() {
+  pkgname=$1
+  target=$2
+  logfile=$3
+
+  echo -n "Building $pkgname: "
+  if ! make -C $SKOOLKIT_HOME $target &> $logfile; then
+    echo "FAILED (see $logfile)"
+    return 1
+  fi
+  echo "OK"
+}
+
+_install_pkg() {
+  pkg=$1
+  cmd=$2
+  logfile=$3
+
+  echo -n "Installing $(basename $pkgname): "
+  if ! sudo $cmd $pkg &> $logfile; then
+    echo "FAILED (see $logfile)"
+    return 1
+  fi
+  echo "OK"
+}
+
+_uninstall_pkg() {
+  cmd=$1
+  logfile=$2
+
+  echo -n "Uninstalling skoolkit: "
+  if ! sudo $cmd skoolkit &> $logfile; then
+    echo "FAILED (see $logfile)"
+    return 1
+  fi
+  echo "OK"
 }
 
 ###############################################################################
@@ -213,15 +253,14 @@ disassembly_diffs() {
   btsdiffsdir=$DISASSEMBLIES_HOME/build/bts-disassembly-diff
   cscdiffsdir=$DISASSEMBLIES_HOME/build/csc-disassembly-diff
   diffslog=diffs.log
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
   DISASSEMBLY_DIFF="$TOOLS/disassembly-diff -t"
 
-  echo -n "Building tarball for version $skversion of SkoolKit: "
+  echo -n "Building tarball for version $VERSION of SkoolKit: "
   $TOOLS/mksktarball -q -t
   echo "OK"
   for d in $mmdiffsdir $jswdiffsdir $sddiffsdir $btsdiffsdir $cscdiffsdir; do
     mkdir -p $d
-    cp -p $SKOOLKIT_HOME/dist/skoolkit-${skversion}.tar.xz $d
+    cp -p $TARBALL $d
     rm -rf $d/disassembly-current-*
   done
 
@@ -256,8 +295,7 @@ disassembly_diffs() {
 # Run check-asms on the MM/JSW/SD/BTS/CSC disassemblies
 ###############################################################################
 check_asms() {
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
-  asmsubdir=disassembly-current-$skversion/asm
+  asmsubdir=disassembly-current-$VERSION/asm
   mmasmdir=$MANICMINER_HOME/build/disassembly-diff/$asmsubdir
   jswasmdir=$JETSETWILLY_HOME/build/disassembly-diff/$asmsubdir
   sdasmdir=$DISASSEMBLIES_HOME/build/sd-disassembly-diff/$asmsubdir
@@ -300,8 +338,7 @@ _create_venv() {
 }
 
 _build_tarball() {
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
-  echo -n "Building tarball for version $skversion of SkoolKit: "
+  echo -n "Building tarball for version $VERSION of SkoolKit: "
   $TOOLS/mksktarball -q -t
   echo "OK"
 }
@@ -309,9 +346,9 @@ _build_tarball() {
 _install_skoolkit() {
   method=$1
 
-  tar xf $SKOOLKIT_HOME/dist/skoolkit-$skversion.tar.xz -C $topdir
-  mv $topdir/skoolkit-$skversion{,-release}
-  cd $topdir/skoolkit-$skversion-release
+  tar xf $TARBALL -C $topdir
+  mv $topdir/skoolkit-$VERSION{,-release}
+  cd $topdir/skoolkit-$VERSION-release
 
   if [[ "$method" = "2" ]]; then
     echo -n "Building source distribution: "
@@ -322,8 +359,8 @@ _install_skoolkit() {
       echo "FAILED (see $logfile)"
       return 1
     fi
-    tar xf dist/skoolkit-$skversion.tar.gz -C $topdir
-    cd $topdir/skoolkit-$skversion
+    tar xf dist/skoolkit-$VERSION.tar.gz -C $topdir
+    cd $topdir/skoolkit-$VERSION
   fi
 
   echo -n "Installing SkoolKit: "
@@ -349,65 +386,64 @@ verify_setup() {
 }
 
 ###############################################################################
-# Build, install and verify a DEB package
+# Build, install, verify and uninstall a DEB package
 ###############################################################################
 build_deb() {
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
-  deb=$SKOOLKIT_HOME/dist/skoolkit_$skversion-1_all.deb
+  debname=skoolkit_$VERSION-1_all.deb
+  deb=$SKOOLKIT_HOME/dist/$debname
   logdir=$SKOOLKIT_HOME/dist
   mkdir -p $logdir
 
   sudo dpkg -r skoolkit &> /dev/null
 
-  echo -n "Building skoolkit_$skversion-1_all.deb: "
-  logfile=$logdir/debuild.log
-  if ! make -C $SKOOLKIT_HOME deb &> $logfile; then
-    echo "FAILED (see $logfile)"
-    exit 1
-  fi
-  echo "OK"
-
-  echo -n "Installing skoolkit_$skversion-1_all.deb: "
-  logfile=$logdir/dpkg-i.log
-  if ! sudo dpkg -i $deb &> $logfile; then
-    echo "FAILED (see $logfile)"
-    exit 1
-  fi
-  echo "OK"
-
+  _build_pkg $debname deb $logdir/debuild.log
+  _install_pkg $deb "dpkg -i" $logdir/dpkg-i.log
   _check_commands /usr/bin $logdir
   _check_man_pages
   _check_resources /usr/share/skoolkit $logdir
   _check_examples /usr/share/skoolkit/examples $logdir
-
-  echo -n "Uninstalling skoolkit: "
-  logfile=$logdir/dpkg-r.log
-  if ! sudo dpkg -r skoolkit > $logfile; then
-    echo "FAILED (see $logfile)"
-    exit 1
-  fi
-  echo "OK"
+  _uninstall_pkg "dpkg -r" $logdir/dpkg-r.log
 
   echo "Now upload $deb to skoolkit.ca"
+}
+
+###############################################################################
+# Build, install, verify and uninstall an RPM package
+###############################################################################
+build_rpm() {
+  rpmname=skoolkit-$VERSION-1.noarch.rpm
+  rpm=$SKOOLKIT_HOME/dist/$rpmname
+  logdir=$SKOOLKIT_HOME/dist
+  mkdir -p $logdir
+
+  sudo rpm -e skoolkit &> /dev/null || true
+
+  _build_pkg $rpmname rpm $logdir/rpmbuild.log
+  _install_pkg $rpm "rpm -i" $logdir/rpm-i.log
+  _check_commands /usr/bin $logdir
+  _check_man_pages
+  _check_resources /usr/share/skoolkit $logdir
+  _check_examples /usr/share/skoolkit/examples $logdir
+  _uninstall_pkg "rpm -e" $logdir/rpm-e.log
+
+  echo "Now upload $rpm to skoolkit.ca"
 }
 
 ###############################################################################
 # Build a source package for uploading to PyPI
 ###############################################################################
 build_sdist() {
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
-  sktarball=$SKOOLKIT_HOME/dist/skoolkit-$skversion.tar.xz
-  if [[ -f $sktarball ]]; then
-    echo "Found $sktarball"
+  if [[ -f $TARBALL ]]; then
+    echo "Found $TARBALL"
   else
-    echo -n "$sktarball not found; building it: "
+    echo -n "$TARBALL not found; building it: "
     $TOOLS/mksktarball -q -t
     echo "OK"
   fi
   cd $(mktemp -d --tmpdir=$HOME/tmp)
   logfile=$(pwd)/sdist.log
-  tar xf $sktarball
-  cd skoolkit-$skversion
+  tar xf $TARBALL
+  cd skoolkit-$VERSION
   echo -n "Building source package: "
   if ./setup.py sdist &> $logfile; then
     echo "OK"
@@ -415,7 +451,7 @@ build_sdist() {
     echo "FAILED (see $logfile)"
     exit 1
   fi
-  sdist=skoolkit-$skversion.tar.gz
+  sdist=skoolkit-$VERSION.tar.gz
   mv dist/$sdist $SKOOLKIT_HOME/dist
   echo "Now upload $SKOOLKIT_HOME/dist/$sdist to PyPI"
 }
@@ -440,8 +476,7 @@ check_pypi() {
 # Build a documentation zip archive for PyPI
 ###############################################################################
 build_doczip() {
-  skversion=$($SKOOLKIT_HOME/skool2html.py -V 2>&1 | cut -f2 -d' ')
-  zipfile=$SKOOLKIT_HOME/dist/skoolkit-$skversion-docs.zip
+  zipfile=$SKOOLKIT_HOME/dist/skoolkit-$VERSION-docs.zip
 
   cd $(mktemp -d --tmpdir=$HOME/tmp)
   echo -n "Cloning local git repository: "
@@ -483,6 +518,7 @@ Pre-release commands:
 
 Post-release commands:
   debpkg - build, install, verify and uninstall a DEB package
+  rpmpkg - build, install, verify and uninstall an RPM package
   bsdist - build a source package for uploading to PyPI
   ifpypi - verify that SkoolKit can be installed from PyPI
   doczip - build a documentation zip archive for PyPI
@@ -500,6 +536,7 @@ case "$1" in
   setup1) verify_setup 1 ;;
   setup2) verify_setup 2 ;;
   debpkg) build_deb ;;
+  rpmpkg) build_rpm ;;
   bsdist) build_sdist ;;
   ifpypi) check_pypi ;;
   doczip) build_doczip ;;
