Make tools/skrelease run the SD/BTS/CSC disassembly tests separately

diff --git a/tools/skrelease b/tools/skrelease
--- a/tools/skrelease
+++ b/tools/skrelease
@@ -174,21 +174,30 @@ test_disassemblies() {
   mkdir -p $JETSETWILLY_HOME/build
   jswlog=$JETSETWILLY_HOME/build/tests.log
   mkdir -p $DISASSEMBLIES_HOME/build
-  sdbtscsclog=$DISASSEMBLIES_HOME/build/tests.log
+  sdlog=$DISASSEMBLIES_HOME/build/sd-tests.log
+  btslog=$DISASSEMBLIES_HOME/build/bts-tests.log
+  csclog=$DISASSEMBLIES_HOME/build/csc-tests.log
 
-  targets=$(echo test{2.7,3.{2,3,4}})
-  make -C $MANICMINER_HOME $targets &> $mmlog & PID1=$!
-  make -C $JETSETWILLY_HOME $targets &> $jswlog & PID2=$!
-  make -C $DISASSEMBLIES_HOME $targets &> $sdbtscsclog & PID3=$!
+  make -C $MANICMINER_HOME test{2.7,3.{2,3,4}} &> $mmlog & PIDmm=$!
+  make -C $JETSETWILLY_HOME test{2.7,3.{2,3,4}} &> $jswlog & PIDjsw=$!
+  make -C $DISASSEMBLIES_HOME test-sd-{2.7,3.{2,3,4}} &> $sdlog & PIDsd=$!
+  make -C $DISASSEMBLIES_HOME test-bts-{2.7,3.{2,3,4}} &> $btslog & PIDbts=$!
+  make -C $DISASSEMBLIES_HOME test-csc-{2.7,3.{2,3,4}} &> $csclog & PIDcsc=$!
 
   echo -n "Manic Miner tests: "
-  wait $PID1 && echo "OK" || echo "FAILED (see $mmlog)"
+  wait $PIDmm && echo "OK" || echo "FAILED (see $mmlog)"
 
   echo -n "Jet Set Willy tests: "
-  wait $PID2 && echo "OK" || echo "FAILED (see $jswlog)"
+  wait $PIDjsw && echo "OK" || echo "FAILED (see $jswlog)"
 
-  echo -n "SD/BTS/CSC tests: "
-  wait $PID3 && echo "OK" || echo "FAILED (see $sdbtscsclog)"
+  echo -n "Skool Daze tests: "
+  wait $PIDsd && echo "OK" || echo "FAILED (see $sdlog)"
+
+  echo -n "Back to Skool tests: "
+  wait $PIDbts && echo "OK" || echo "FAILED (see $btslog)"
+
+  echo -n "Contact Sam Cruise tests: "
+  wait $PIDcsc && echo "OK" || echo "FAILED (see $csclog)"
 }
 
 ###############################################################################
