Simplify gen_snapshot() in tools/write-files

diff --git a/tools/write-files b/tools/write-files
--- a/tools/write-files
+++ b/tools/write-files
@@ -23,12 +23,9 @@ run_cmd() {
 }
 
 gen_snapshot() {
-  if [ ! -f $SNAPSHOT ]; then
-    t2s=$(ls $DHOME/*.t2s)
-    if ! ./tap2sna.py @$t2s $SNAPSHOT; then
-      echo -e "\e[0;31mFailed to generate $SNAPSHOT\e[0m"
-      exit 1
-    fi
+  if ! make -sC $DHOME snapshot; then
+    echo -e "\e[0;31mFailed to generate $SNAPSHOT\e[0m"
+    exit 1
   fi
 }
 
